#+title: Asignación de memoria
#+author: Gunnar Wolf

- Edgar Guadarrama ::
  - Código :: [[./GuadarramaEdgar/tarea2.c][tarea2.c]]
  - Lenguaje :: C
  - Comentarios ::
    - ¡Muy bien resuelto!
    - Recomendación: Estás utilizando los comentarios como
      micro-documentación de uso. Si bien es válido en una tarea, te
      crea malas prácticas a futuro. Los comentarios deben ser
      información útil /al programador/ que se acerque a tu código. La
      documentación (como tus líneas 117 y 121) debería ser un archivo
      aparte, orientado a tus /usuarios/.
  - Calificación :: 10

- Aníbal Medina y Guadalupe Moreno ::
  - Código :: [[./MorenoGuadalupe-MedinaAnibal/Asignador.java][Asignador.java]]
  - Lenguaje :: Java
  - Comentarios ::
    - ¡Buena implementación! (¿ven cómo sí soy capaz de decir eso de
      un programa en Java? ☺)
    - Cómodo y útil que los procesos que se vayan asignando vayan
      tomando letras y tamaños aleatorios. Sin embargo, dado que no
      reporta el tamaño del proceso que intentaría asignar, tuve que
      "picarle" varias veces para convencerme de que no implementa
      compactación. Vamos:
      #+BEGIN_SRC text
      Entra proceso (W) de tamaño 10
      CCCHHHIIIIIIIIIIIIIWWWWWWWWWW-

      s
      Se eliminó al proceso H
      CCC---IIIIIIIIIIIIIWWWWWWWWWW-

      a
      No hay espacio suficiente para el proceso D
      CCC---IIIIIIIIIIIIIWWWWWWWWWW-

      a
      Entra proceso (X) de tamaño 2
      CCCXX-IIIIIIIIIIIIIWWWWWWWWWW-
      #+END_SRC
    - Y, sí... Les faltó implementar la compactación.
  - Calificación :: 9

- Miguel Pérez ::
  - Código :: [[./PerezMiguel/Memoria.java][Memoria.java]], [[./PerezMiguel/TestMemoria.java][TestMemoria.java]]
  - Lenguaje :: Java
  - Comentarios ::
    - ¡Bien! Asigna, libera, compacta, reporta errores... ¿Qué más
      puedo pedir? ☺
    - Tu código no compila tal como lo mandaste:
      #+BEGIN_SRC text
	$ javac TestMemoria.java 
	./Memoria.java:140: error: cannot find symbol
			if(Tabla.asigna(nombre, tamanio) == 1)
			   ^
	  symbol:   variable Tabla
	  location: class Memoria
	1 error
      #+END_SRC
      Basta con quitar =Tabla.= para que funcione. ¿Qué pasó ahí? :-]
  - Calificación :: 10

- Simón Ramírez y Cristian Valeriano ::
  - Código :: [[./RamirezSimon-ValerianoCristian/asigMem.rb][asigMem.rb]]
  - Lenguaje :: ruby
  - Comentarios ::
    - Tienen varios errores de uso de métodos erróneos
      (=String#include= no existe para =cadena.include(cad_aux)=
      repetidamente)
    - =String#succ= entrega una cadena nueva, no modifica a la
      existente (hay que re-asignar a procesos)
    - Hay varios puntos en que la =cadena= no es pasada a la función,
      por lo que el programa no llega a funcionar. Lo evalúo
      únicamente basado en el fuente.
    - La lógica de =asignaProceso()= suena correcta, y me gusta el uso
      que hacen del lenguaje. La lógica de =liberaProceso()= llevaría
      efectivamente a una compactación siempre que termine un proceso
      - Podrías usar =String.gsub!()=:
	#+BEGIN_SRC text
	  >> v='AAAA--BBBBCCDDDD'.ljust(30,'-')
	  => "AAAA--BBBBCCDDDD--------------"
	  >> v.gsub!('C', '-')
	  => "AAAA--BBBB--DDDD--------------"
	  >> v.gsub!('B', '-')
	  => "AAAA--------DDDD--------------"
	#+END_SRC
  - Calificación :: 8

- Miguel Aguilar ::
  - Código :: [[./AguilarMiguel/asignador.c][asignador.c]]
  - Lenguaje :: C
  - Comentarios ::
    - Tu programa depende de un archivo que indique cómo
      asignar/emplear la memoria. Este archivo debe seguir un formato
      en específico. ¡Pero no incluyes documentación! Tuve que generar
      el archivo básicamente por /ingeniería inversa/ — Viendo lo que
      tu programa /busca hacer/ con él.
    - Tu programa en general es /muy bueno/ — Con un par de
      anotaciones importantes, sí, pero la forma en que lo resolviste
      es muy buena.
      - En primer lugar, solicité /asignación contigua/. Tu programa
        asigna espacio en memoria incluso si no puede satisfacerse. Al
        detectar que la memoria no puede asignarse de forma contigua,
        deberías forzar una /compactación/
      - En segundo lugar, tu función =asigMemoria()= no contempla el
        caso de que no haya memoria suficiente para satisfacer la
        solicitud. Si bien verificas y podrías imprimir =No se pudo
        asignar= (línea 110), nunca llegas ahí. Por ejemplo, indicando
        las siguientes solicitudes, tu programa se queda en un ciclo
        eterno, nomás quemando CPU:
	#+BEGIN_SRC text
	1 14
	2 3
	#+END_SRC
  - Calificación :: 0 (entrega más de una semana después de la fecha límite)

- Karla Guzmán ::
  - Código :: [[./GuzmánKarla/asigmem.py][asigmem.py]]
  - Lenguaje :: Python
  - Comentarios ::
    - Buena implementación, aunque con un par de detalles
    - Al intentar quitar un proceso, Python manda un error:
      #+BEGIN_SRC text
	1 => Agregar proceso
	2 => Quitar proceso
	0 => Salir
	$$ 2
	ingresa el nombre del proceso: Z
	Traceback (most recent call last):
	  File "asigmem.py", line 110, in <module>
	    control()
	  File "asigmem.py", line 108, in control
	    opcion(numero)
	  File "asigmem.py", line 94, in opcion
	    vacia_memoria(proceso, tamano)
	  File "asigmem.py", line 31, in vacia_memoria
	    while contador1 > 0:
	UnboundLocalError: local variable 'contador1' referenced before assignment
      #+END_SRC
      Esto es porque estás asignando (línea 30) un valor a la variable
      =contador=, pero en la siguiente línea la utilizas como
      =contador1=. Corrigiendo el nombre de la variable, el programa
      funciona bien.
    - Tu programa detecta correctamente la compactación de memoria,
      /pero no la efectúa/, y realiza asignación de memoria no
      contigua:
      #+BEGIN_SRC text
	1 => Agregar proceso
	2 => Quitar proceso
	0 => Salir
	$$ 1
	ingresa el nombre del proceso: G
	ingresa el tamaño de tu proceso: 6
	se requiere compactar la memoria

	Mapa de memoria 

	|A| |A| |A| |A| |A| |A| |A| |A| |A| |A| 

	|A| |A| |A| |A| |A| |G| |G| |G| |B| |B| 

	|B| |R| |R| |R| |R| |G| |G| |G| |*| |*| 
      #+END_SRC
  - Calificación :: 0 (entrega más de una semana después de la fecha límite)

- Andrew Sánchez ::
  - Código :: [[./SanchezAndrew/Tarea2.py][Tarea2.py]]
  - Documentación :: [[./SanchezAndrew/Documentacion.txt][Documentacion.txt]]
  - Lenguaje :: Python
  - Comentarios ::
    - El programa es básicamente el mismo que el entregado por Karla
      Guzmán, los comentarios a aquel valen para este
    - No hay problema, el problema estaba planteado para resolverse
      /de forma individual o en equipos de 2 personas/ 😉
      - Además... De todos modos, no alcanzaron calificación ☹
  - Calificación :: 0 (entrega más de una semana después de la fecha límite)

- Luis Chibras ::
  - Código :: [[./ChibrasLuis/tarea2.py][tarea2.py]]
  - Lenguaje :: Python
  - Comentarios ::
    - El programa tiene varios errores de implementación, no logré
      correrlo ejecutarlo exitosamente
      - En =menu()=, el valor recibido en =opcion= no es una cadena
        (siempre da falso cuando lo comparas con ='0'= o ='1'=). Ya
        sea que lo conviertes en una o que comparas con el entero
        correspondiente.
      - La lógica de =Borrar()= me parece correcta a grandes rasgos,
        pero falla al intentar evluar al nombre del proceso solicitado
        (=NameError: name 'A' is not defined=).
      - Me parece que tu fallo al iniciar se presenta cuando generas
        una cadena que no puede satisfacerse (p.ej. se excede el
        tamaño de la memoria(?): Tu =while= busca la condición =ar
        !=0=, pero cuando asignas espacio, disminuyes =ar= dos veces
        (y puede pasar de =1= a =-1=).

  - Calificación :: 0 (entrega más de una semana después de la fecha límite)

- Alejandro Pérez ::
  - Código :: [[./PerezAlejandro/mem.py][mem.py]]
  - Documentación :: [[./PerezAlejandro/doc.pdf][doc.pdf]]
  - Lenguaje :: Python
  - Comentarios ::
    - No detecta ni realiza compactación, "rompe" un proceso en
      secciones si no hay un espacio contiguo adecuado:
      #+BEGIN_SRC text
	1. Agregar proceso
	2. Quitar proceso
	0. Salir
	>> 1
	Ingresa el nombre del proceso: T
	Ingresa el tamaño del proceso: 6
	Se requiere compactación de memoria
	sh: 1: cls: not found

	───────────────── MEMORY MAP ─────────────────

	 F   F   F   F   E   E   E   T   T   T  

	 T   T   R   R   R   R   R   R   T   -  

	 -   L   L   L   L   L   L   L   L  
      #+END_SRC

  - Calificación :: 8 × 0.8 = 6.4 (subido a Git a tiempo, pero
                    entregado mucho después)
